const $=id=>document.getElementById(id);
const views=["home","chat","voice","images","website","story","personality"];
let activeView="home", selectedStyle="Photorealistic", selectedGenre="Fantasy", tone="Friendly", length="balanced", useEmoji=true, customInstructions="", lastReply="Hey! I'm Solire. What would you like to create today?", chatImage=null;
function toast(msg){$("toast").textContent=msg;$("toast").classList.remove("hidden");clearTimeout(toast.timer);toast.timer=setTimeout(()=>$("toast").classList.add("hidden"),2200)}
function showView(v){if(!views.includes(v))v="home";activeView=v;views.forEach(x=>$(x+"View").classList.toggle("hidden",x!==v));document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("active",b.dataset.view===v));const names={home:"Home",chat:"Chat",voice:"Voice",images:"Images",website:"Websites",story:"Stories",personality:"Personality"};$("crumb").textContent=names[v];window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));
$("openPrefs").addEventListener("click",()=>showView("personality"));$("topPrefs").addEventListener("click",()=>showView("personality"));
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function replyFor(s){let m=s.toLowerCase(),r;if(/^(hi|hey|hello|yo)\b/.test(m))r="Hey! What are we creating today?";else if(m.includes("image")||m.includes("draw")||m.includes("picture"))r="Let's make a great image prompt. Head to Images, describe your idea, and choose a style. This version prepares the prompt; a connected image model is needed to render an actual picture.";else if(m.includes("website")||m.includes("html")||m.includes("css"))r="Open Websites and describe the site you want. I can build a local starter template with editable index.html and style.css plus a preview.";else if(m.includes("story")||m.includes("book"))r="Let's build a world! Open Stories, enter your idea, choose a genre and chapter count, and generate an editable story starter.";else if(m.includes("help"))r="I can help brainstorm, write, outline stories, prepare image prompts, create website templates, and chat using your selected personality. Voice uses your browser's speech tools.";else r="Here's one way to get started:\n\n1. Define what you want the result to do.\n2. Make a simple first version.\n3. Improve the details one at a time.\n\n"+(customInstructions? "Your preference: "+customInstructions:"Tell me a little more about your idea and I can help shape it.");if(tone==="Professional")r=r.replace("Hey!","Hello.").replace(/!/g,".");if(tone==="Witty")r="Let's make something delightfully unboring. ✨\n\n"+r;if(tone==="Poetic")r="Every good idea starts as a tiny spark. ✦\n\n"+r;if(tone==="Blunt")r=r.split("\n\n")[0];if(tone==="Gen-Z")r="Okay, let's cook. ✌️\n\n"+r;if(tone==="Pirate")r="Ahoy! ⚓\n\n"+r;if(tone==="Wise mentor")r="Take it one step at a time. Here's a path forward:\n\n"+r;if(!useEmoji)r=r.replace(/[✨✦✌️⚓☺]/g,"");if(length==="short")r=r.split("\n\n")[0];if(length==="detailed")r+="\n\nNext, we can refine the goal, choose a style, and work through the details together.";return r}
function addChat(role,text){const row=document.createElement("div");row.className="chat-message "+role;const icon=document.createElement("div");icon.className="bubble-icon";icon.textContent=role==="bot"?"✦":"◉";const body=document.createElement("div"),b=document.createElement("b"),p=document.createElement("p");b.textContent=role==="bot"?"Solire":"You";p.textContent=text;body.append(b,p);row.append(icon,body);$("chatArea").append(row);$("chatArea").scrollTop=$("chatArea").scrollHeight}
$("chatForm").addEventListener("submit",e=>{e.preventDefault();let s=$("chatText").value.trim();if(!s)return;addChat("user",s);$("chatText").value="";lastReply=replyFor(s);setTimeout(()=>addChat("bot",lastReply),120)});
$("chatText").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("chatForm").requestSubmit()}});
$("chatUpload").addEventListener("change",e=>{let f=e.target.files[0];if(!f)return;if(chatImage)URL.revokeObjectURL(chatImage);chatImage=URL.createObjectURL(f);$("chatImagePreview").classList.remove("hidden");$("chatImagePreview").innerHTML="";let im=document.createElement("img");im.src=chatImage;im.alt=f.name;$("chatImagePreview").append(im);toast("Image ready to reference in this demo")});
document.querySelectorAll(".style-choice").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".style-choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selectedStyle=b.dataset.style}));
$("makeImage").addEventListener("click",()=>{let p=$("imagePrompt").value.trim();if(!p){$("imagePrompt").focus();toast("Describe your image first");return}let out=`${p}\n\nStyle: ${selectedStyle}\nAspect ratio: ${$("imageRatio").value}\nDetail: ${$("imageQuality").value}\nComposition: clear focal subject, cohesive color palette, intentional lighting, balanced composition, polished finish.`;$("imageResult").classList.remove("hidden");$("imageResultText").textContent=out});
document.querySelectorAll("[data-copy]").forEach(b=>b.addEventListener("click",()=>copy($($(b).dataset.copy).textContent)));
document.querySelectorAll(".suggest").forEach(b=>b.addEventListener("click",()=>{$("sitePrompt").value=b.dataset.prompt}));
function makeSite(prompt){let title="My Creative Website",heading="A fresh idea, brought to life.",desc=prompt||"A modern, welcoming website.";if(/coffee/i.test(prompt)){title="Ember Coffee";heading="Your new favorite corner.";desc="Thoughtful coffee. Good people. Slow mornings."}else if(/pizza/i.test(prompt)){title="Slice House";heading="Good pizza. Great company.";desc="Fresh dough, bold flavors, and a slice for everyone."}else if(/photograph|portfolio/i.test(prompt)){title="Alex Morgan — Photography";heading="Stories, captured in light.";desc="A curated portfolio of moments, places, and people."}else{let match=prompt.match(/(?:for|called|named)\s+([A-Z][\w -]{2,30})/);if(match)title=match[1].trim();}const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><link rel="stylesheet" href="style.css"></head><body><nav><b>${esc(title)}</b><div><a href="#about">About</a><a href="#features">Highlights</a><a href="#contact">Contact</a></div></nav><main><section class="hero"><span class="tag">MADE WITH PURPOSE</span><h1>${esc(heading)}</h1><p>${esc(desc)}</p><a class="cta" href="#contact">Let's get started ↗</a></section><section id="features" class="features"><article><span>✦</span><h2>Made for you</h2><p>Thoughtful details and a clear point of view.</p></article><article><span>◈</span><h2>Simple by design</h2><p>Everything you need, without the clutter.</p></article><article><span>↗</span><h2>Ready to explore</h2><p>A starting point for your next big idea.</p></article></section><section id="about" class="about"><h2>A little about us</h2><p>${esc(desc)} We believe the best experiences are useful, welcoming, and memorable.</p></section><section id="contact" class="contact"><h2>Let's make it happen.</h2><p>Have a question or an idea? We'd love to hear from you.</p><form><input placeholder="Your email address" type="email" aria-label="Email address"><button>Say hello</button></form></section></main><footer>© 2026 ${esc(title)} · Made with care</footer></body></html>`;
const css=`*{box-sizing:border-box}body{margin:0;background:#f8f6f2;color:#28251f;font-family:Arial,sans-serif}nav{height:70px;padding:0 7%;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #e9e2d9;background:#fff}nav b{font-size:18px}nav a{color:#666;text-decoration:none;font-size:12px;margin-left:22px}main{max-width:1050px;margin:auto;padding:0 25px}.hero{text-align:center;padding:90px 0 75px}.tag{font-size:10px;letter-spacing:2px;color:#7d6d56;font-weight:bold}.hero h1{font-size:clamp(35px,6vw,62px);letter-spacing:-2px;line-height:1.05;max-width:750px;margin:22px auto}.hero p{font-size:15px;color:#777;line-height:1.7;max-width:520px;margin:0 auto 25px}.cta{display:inline-block;padding:13px 20px;background:#29251f;color:white;text-decoration:none;border-radius:6px;font-size:12px}.features{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;padding:25px 0 60px}.features article{background:white;border:1px solid #eee7de;padding:23px;border-radius:12px}.features article span{font-size:24px;color:#987d59}.features h2,.about h2,.contact h2{font-size:20px}.features p,.about p,.contact p{font-size:13px;line-height:1.7;color:#777}.about{padding:38px 0;border-top:1px solid #e9e2d9;max-width:680px}.contact{background:#eee8de;border-radius:14px;padding:35px;margin:25px 0 55px}.contact form{display:flex;gap:8px;margin-top:18px}.contact input{flex:1;min-width:0;border:1px solid #ddd3c6;border-radius:6px;padding:12px}.contact button{border:0;background:#29251f;color:white;padding:12px 17px;border-radius:6px}footer{text-align:center;border-top:1px solid #e9e2d9;padding:23px;color:#888;font-size:11px}@media(max-width:600px){nav{padding:0 18px}nav a{margin-left:10px;font-size:10px}.hero{padding:65px 0 45px}.features{grid-template-columns:1fr}.contact form{flex-direction:column}}`;
return {html,css}}
$("buildSite").addEventListener("click",()=>{let p=$("sitePrompt").value.trim();if(!p){$("sitePrompt").focus();toast("Describe the website first");return}let site=makeSite(p);$("htmlCode").value=site.html;$("cssCode").value=site.css;$("siteResult").classList.remove("hidden");updatePreview();toast("Website template generated")});
function updatePreview(){let h=$("htmlCode").value,c=$("cssCode").value;let combined=h.replace('<link rel="stylesheet" href="style.css">',`<style>${c.replace(/<\/style/gi,"<\\/style")}</style>`);$("sitePreview").srcdoc=combined}
document.querySelectorAll(".code-tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".code-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("htmlCode").classList.toggle("hidden",b.dataset.code!=="html");$("cssCode").classList.toggle("hidden",b.dataset.code!=="css")}));
$("htmlCode").addEventListener("input",updatePreview);$("cssCode").addEventListener("input",updatePreview);
$("downloadSite").addEventListener("click",()=>{download("index.html",$("htmlCode").value);download("style.css",$("cssCode").value);toast("Downloaded HTML and CSS")});
$("siteUpload").addEventListener("change",e=>{let f=e.target.files[0];if(f)toast("Reference image selected: "+f.name+" (not sent to a server)")});
document.querySelectorAll(".genre").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".genre").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selectedGenre=b.dataset.genre}));
$("makeStory").addEventListener("click",()=>{let idea=$("storyIdea").value.trim();if(!idea){$("storyIdea").focus();toast("Add your story idea first");return}let n=Math.max(1,Math.min(12,Number($("chapters").value)||4)),title=idea.split(/[.!?]/)[0].slice(0,52)||"The New Beginning";let text=`${title}\nA ${selectedGenre} story · For ${$("storyFormat").value}\n\nSTORY IDEA\n${idea}\n\nPROLOGUE\nEvery world has a secret. This one had been waiting patiently for someone curious enough to notice it. At first, the day seemed ordinary — the same familiar sounds, the same paths, the same little routines. Then one small detail refused to fit.\n\n${idea}\n\nThe discovery raised a question no one else seemed ready to ask. Our main character could ignore it and return to the comfortable shape of ordinary life, or take one careful step toward the unknown. They took a breath, gathered their courage, and stepped forward.\n\n`;for(let i=1;i<=n;i++){text+=`CHAPTER ${i}: ${["The Unusual Discovery","A Door Opens","The First Obstacle","Unexpected Allies","A Difficult Choice","The Hidden Truth","Into the Unknown","A Change of Plan","The Great Test","A New Perspective","The Final Clue","A New Beginning"][i-1]}\n\nThe next part of the journey began with a choice. ${idea} The path ahead was uncertain, but each clue made the larger picture a little clearer. A new challenge appeared, asking the characters to think differently and trust what they had learned. By the end of this chapter, one thing had changed forever — and a bigger question waited just beyond the horizon.\n\n`}text+="\nAUTHOR'S NOTE\nDevelop each chapter with a specific scene, a character decision, and a consequence. Add dialogue, sensory details, and surprises that connect to the central idea."; $("storyTitle").textContent=title;$("storyText").value=text;$("storyResult").classList.remove("hidden")});
$("saveStory").addEventListener("click",()=>download("solire-story.txt",$("storyText").value));
document.querySelectorAll(".tone").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tone").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");tone=b.dataset.tone}));
document.querySelectorAll(".length").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".length").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");length=b.dataset.length}));
$("savePersonality").addEventListener("click",()=>{useEmoji=$("useEmoji").checked;customInstructions=$("customInstructions").value.trim();$("savedMsg").classList.remove("hidden");toast("Personality saved for this session")});
function download(name,text){let blob=new Blob([text],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null;if(SR){recognition=new SR();recognition.lang="en-US";recognition.interimResults=true;recognition.onstart=()=>{$("voiceStatus").textContent="Listening…";$("listen").textContent="Listening…"};recognition.onresult=e=>{let s="";for(let i=e.resultIndex;i<e.results.length;i++)s+=e.results[i][0].transcript;$("voiceTranscript").textContent=s;if(e.results[e.results.length-1].isFinal){lastReply=replyFor(s);addChat("user",s);addChat("bot",lastReply);$("voiceStatus").textContent="Solire has a reply";}};recognition.onerror=e=>$("voiceStatus").textContent="Voice error: "+e.error;recognition.onend=()=>{$("listen").textContent="🎙 Start talking"}}
$("listen").addEventListener("click",()=>{if(!recognition){$("voiceStatus").textContent="Speech recognition is not supported here. Try Chrome or Edge.";return}try{recognition.start()}catch{$("voiceStatus").textContent="Already listening"}});
$("sayLast").addEventListener("click",()=>{if(!("speechSynthesis"in window)){toast("Text-to-speech not supported in this browser");return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(lastReply);speechSynthesis.speak(u);$("voiceStatus").textContent="Speaking…";u.onend=()=>$("voiceStatus").textContent="Ready when you are"});
